body {
    font-family: Arial, sans-serif;
    display: flex;
    justify-content: center;
    align-items: center;
    min-height: 100vh;
    margin: 0;
    background-color: #f4f4f4;
    color: #333;
}

.container {
    background-color: #fff;
    padding: 30px;
    border-radius: 8px;
    box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
    text-align: center;
    width: 90%;
    max-width: 500px;
}

h1 {
    color: #007bff;
    margin-bottom: 25px;
}

.input-group {
    margin-bottom: 20px;
}

.input-group label {
    display: block;
    margin-bottom: 8px;
    font-weight: bold;
}

.input-group input[type="text"] {
    width: calc(100% - 22px); /* หัก padding + border */
    padding: 10px;
    margin-right: 10px;
    border: 1px solid #ccc;
    border-radius: 4px;
    font-size: 16px;
    box-sizing: border-box; /* ทำให้ padding ไม่เพิ่มขนาดรวม */
}

.input-group button {
    padding: 10px 20px;
    background-color: #007bff;
    color: white;
    border: none;
    border-radius: 4px;
    cursor: pointer;
    font-size: 16px;
    transition: background-color 0.3s ease;
}

.input-group button:hover {
    background-color: #0056b3;
}

.status-result {
    margin-top: 30px;
    padding: 20px;
    border: 1px dashed #007bff;
    border-radius: 6px;
    background-color: #e9f5ff;
    min-height: 50px; /* ให้มีพื้นที่แสดงผล */
    text-align: left;
}

.status-result p {
    margin: 5px 0;
    font-size: 1.1em;
}

.status-result strong {
    color: #0056b3;
}

.status-result .not-found {
    color: #dc3545;
    font-weight: bold;
    text-align: center;
}
